### ISSUE TITLE
"header.html" missing

### ISSUE THREAD

**Issue by AkihiroSuda** [cyphar/rootlesscontaine.rs#3]
https://github.com/cyphar/rootlesscontaine.rs/blob/512569b6ee94d77499b456fc623e600d8e6ec64a/site/layouts/index.html#L1

@cyphar Could you add header.html so that the Hugo sources can be compiled?

p.s. I'd like to add my "runROOTLESS" project to the list after this issue gets fixed 😄 : https://github.com/AkihiroSuda/runrootless

**Comment by cyphar** [comment]
The source is in `./site/themes/base16/layouts/partials/header.html` -- you need to clone this repo recursively to get the `base16` submodule which contains all the theme partials.

**Comment by AkihiroSuda** [comment]
uh, sorry

**Comment by cyphar** [comment]
Don't sweat it.
